[tool.poetry]
name = "markbench-tests"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
pywinauto = {version = "0.6.8", platform = "win32"}
pyyaml = "6.0"
python-dotenv = "0.20.0"
pyfiglet = "0.8.post1"
PyAutoGUI = "^0.9.53"
PyDirectInput = {version = "^1.0.4", platform = "win32"}
opencv-python = "^4.5.5"
Pillow = "^9.1.1"
psutil = "^5.9.1"
pandas = "^1.4.2"
imutils = "^0.5.4"
matplotlib = "^3.5.2"
protobuf = "^4.21.2"
WMI = {version = "^1.5.1", platform = "win32"}
mss = "^7.0.1"
requests = "^2.28.2"
vdf = {version = "^3.4", platform = "linux"}

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = "^6.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# https://docs.pytest.org/en/6.2.x/reference.html#ini-options-ref
[tool.pytest.ini_options]
testpaths = ["./tests"]

