friendly_name = "3DMark"
py_script = "ul3dmark.py"
executable = "3DMarkCmd.exe"
presentmon_enabled = false
non_game = true

[[args]]
name = "benchmark"
type = "select"
tooltip = "Select which 3DMark scene to run"
values = ["TimeSpy", "FireStrike", "PortRoyal", "SolarBay"]
