friendly_name = "GravityMark"
py_script = "gravitymark.py"
executable = "GravityMark.exe"
presentmon_enabled = false
non_game = true

[[args]]
name = "api"
type = "select"
tooltip = "Select which Graphics API to use"
values = ["vulkan", "opengl", "direct3d12", "direct3d11"]
